### ISSUE TITLE
Import discrepancy

### ISSUE THREAD

**Issue by DiazBejaranoD** [amazon-science/intent-aware-encoder#4]
Testing code for the IRL part and found a circular import problem. I'm guessing line 20 of file /pretraining/preprocess/irl/irl_tagger is wrong, as module to be imported in that line seem to come from a different file.
I guess it should **from irl.data import LabeledSpan**
instead of **from irl.intent_role_labelers import LabeledSpan**

**Comment by jgung** [comment]
@DiazBejaranoD thanks a lot for pointing this out! Should be addressed in #6.
