### ISSUE TITLE
irl model missing in configured path

### ISSUE THREAD

**Issue by DiazBejaranoD** [amazon-science/intent-aware-encoder#5]
pretraining create_dataset.sh script points to a model location that does not exist, yielding 

raise FileNotFoundError(f"file {url_or_filename} not found")
FileNotFoundError: file **../models/irl_model/irl-model-sgd-08-16-2022.tar.gz** not found

Directory models in the root dir does not exist.

**Comment by chen989898** [comment]
我也遇到了请问解决了吗

**Comment by chen989898** [comment]
> 预训练 create_dataset.sh 脚本指向不存在的模型位置，产生
> 
> 引发 FileNotFoundError(f"文件 {url_or_filename} 未找到") FileNotFoundError: 文件**../models/irl_model/irl-model-sgd-08-16-2022.tar.gz**未找到
> 
> 根目录中的目录模型不存在。


我也遇到了这个问题，请问解决了吗

**Comment by jgung** [comment]
Hi @DiazBejaranoD and @chen989898, thank you for your interest in this project and for raising this issue.

Unfortunately, we're unable to release the original model at this time. However, I've updated the repo in #6, providing instructions and scripts for training the IRL model using the provided dataset [here](https://github.com/amazon-science/intent-aware-encoder/tree/main/data). Let us know if you have any further questions!
